//
// Created by imanuel on 05.11.19.
//

#ifndef TERRARIUM_MEASURE_AND_CONTROL_SYMBOLS_H
#define TERRARIUM_MEASURE_AND_CONTROL_SYMBOLS_H
#define DEBUG 1

#endif //TERRARIUM_MEASURE_AND_CONTROL_SYMBOLS_H
